extends: airbnb
env:
  browser: true
  node: true
  jest: true
plugins:
  - import
rules:
  strict: off
  no-console: off
  max-len: off
  prefer-rest-params: off
  prefer-spread: off
  no-warning-comments: error
  import/no-extraneous-dependencies: off
  react/require-default-props: off
  import/no-named-as-default: off
  react/jsx-filename-extension: off
